spring.application.name=VideoStreaming

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}

aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.region=${AWS_REGION}
aws.s3.endpoint=${AWS_ENDPOINT:}
aws.s3.path-style-access-enabled=${AWS_PATH_STYLE_ACCESS_ENABLED:false}

management.endpoints.web.exposure.include=*

spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.max-file-size=1GB

logging.level.org.springframework.security=TRACE

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION}
security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}